.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.isort.cfg
.pre-commit-config.yaml

Hi,
here are some changes and additions which I would propose:
* Black and isort now also adhere to the 125 character line length.
* Updated the versions of all pre-commit hooks by running `pre-commit autoupdate`
* Adapted the issue templates from FINN. (These will like need some more looking over and might need a better way to contact the hls4ml team and community, or it might be useful to create a gitter channel just for this repo.)

Extended line length limit for more linting tools, updated linting tools and added issue templates.

---

CITATION.cff
README.md

- README + CITATION update
For now, the Zenodo DOI is a dummy (it gets automatically generated once we create a release). If we want we could create a "dummy" release now just so we get the DOI. 
We should probably add a lot more contributors to the `CITATION.cff`.

README + CITATION update

---

src/qonnx/transformation/general.py
tests/transformation/test_general_transformation.py

When the parameter to the `Div` node is scalar, the `DivToMul` transformation performs a computation that causes the transformed tensor to change type to `np.float64`. This PR introduces a test case that reproduces this problem and fixes the issue by casting the new tensor's datatype to be the same as the original one's.

Fix datatype for scalar DivToMul

---

src/qonnx/transformation/infer_datatypes.py

When inferring the datatype of the tensors, the output tensor of the Add operator would by default have a FLOAT32 annotation.
Given that the input datatypes are integer, we want to annotate the output tensor of the Add operator with (U)INT32.

Infer output datatype of Add (ONNX) operator

---

src/qonnx/transformation/infer_shapes.py

To perform shape inference for custom nodes, we currently replace each custom node with a standard node that produces an output tensor of the desired output shape (as returned by the `make_shape_compatible_op` function). This small PR adds a change that keeps the previous ONNX node name for the newly created node, which can help debug shape inference issues when something fails.

Keep node names during shape inference to help debug

---

src/qonnx/custom_op/general/maxpoolnhwc.py

Previous implementation was using incorrect index from the `pads` attribute for the width dimension. For a 2D maxpool this attribute specifies `(pad_h_start, pad_w_start, pad_h_end, pad_w_end)`

Fix MaxPoolNHWC output shape computation

---

src/qonnx/transformation/rebalance_conv.py
tests/transformation/test_rebalance_conv.py

New transformation `RebalanceIm2Col`: For certain hardware that prefers channel parallelism over feature map spatial parallelism, it is possible to reshape the inputs to an `Im2Col` node to move some of the spatial dimension into the channels dimension. This transformation attempts to find such `Im2Col` nodes, adds a `Reshape` node in front and alters their kernel/stride sizes accordingly. See list of conditions checked in the implementation for a full list, but one example of
rebalancing is provided in the unit test for this transformation (`test_rebalance_conv.py`)

New transformation: Im2Col rebalancing for certain cases

---

src/qonnx/custom_op/base.py
tests/custom_op/test_attr.py

Support tensor attributes as part of `CustomOp`s, values are carried as numpy arrays and converted appropriately into ONNX `TensorProto` for storage.

Support tensor attributes

---

src/qonnx/util/basic.py
tests/util/test_matvec_range.py

Using all of the matrix rather than just the min/max.

Updating matvec accumulator range calculation

---

src/qonnx/custom_op/base.py
src/qonnx/custom_op/channels_last/conv.py
src/qonnx/custom_op/channels_last/max_pool.py

For `CustomOp` instances that use an attribute of ONNX dtype `ints`, convert to a regular Python list as part of the getter since the underlying protobuf `RepeatedScalarContainer` causes e.g. JSON serialization issues.

Typecast ints attributes to list for better behavior

---

notebooks/0_how_to_work_with_onnx.ipynb
notebooks/1_custom_analysis_pass.ipynb
notebooks/2_custom_transformation_pass.ipynb
notebooks/3_custom_op.ipynb
setup.cfg
src/qonnx/core/onnx_exec.py
src/qonnx/custom_op/channels_last/base_wrapped_op.py
src/qonnx/custom_op/general/maxpoolnhwc.py
src/qonnx/custom_op/general/quantavgpool2d.py
src/qonnx/transformation/merge_onnx_models.py
src/qonnx/util/basic.py
tests/analysis/test_is_linear.py
tests/analysis/test_topology_checks.py
tests/core/test_basic_onnx_exec.py
tests/core/test_mixed_onnx_exec.py
tests/core/test_modelwrapper.py
tests/custom_op/test_im2col.py
tests/custom_op/test_xnorpopcountmatmul.py
tests/transformation/test_4d_conversion.py
tests/transformation/test_batchnorm_to_affine.py
tests/transformation/test_change_datalayout.py
tests/transformation/test_conv_lowering.py
tests/transformation/test_extend_partition.py
tests/transformation/test_general_transformation.py
tests/transformation/test_generic_partitioning.py
tests/transformation/test_merge_onnx_models.py
tests/transformation/test_remove_identity_ops.py
tests/transformation/test_sort_graph.py

Change the pinned dependency package versions as follows:
`protobuf==3.20.1` --> `protobuf==3.20.3`
`onnx==1.11.0` -->    `onnx==1.13.0`
Note that the version changes in onnx break how test models are created in the qonnx test code, so a new utility function `qonnx_make_model` that explicitly sets the opset version is introduced for creation of test models. Opset 9 is preferred but can be overridden at model creation time. Relevant qonnx tests have been updated to use this function instead of the `onnx.helper.make_model`

Update onnx and protobuf versions

---

src/qonnx/core/execute_custom_node.py
src/qonnx/core/onnx_exec.py
src/qonnx/custom_op/base.py
src/qonnx/custom_op/channels_last/base_wrapped_op.py
src/qonnx/custom_op/channels_last/conv.py
src/qonnx/custom_op/channels_last/max_pool.py
src/qonnx/custom_op/registry.py
src/qonnx/transformation/channels_last.py
src/qonnx/util/cleanup.py
tests/transformation/test_channelslast.py

Hi,
this PR addresses the issue that channels last ops have currently no way of telling which onnx opset version is supposed to be used for inference.
To this end the base class for custom ops as been extended to carry this information and the execution functions have been extended to pass it along.

Add ability to pass onnx opset information to custom ops 

---

src/qonnx/custom_op/channels_last/conv.py
src/qonnx/custom_op/channels_last/max_pool.py
src/qonnx/transformation/channels_last.py
src/qonnx/util/cleanup.py
tests/transformation/test_channelslast.py

As reported in #32, the channels-last conversion currently fails for Conv operators with a bias and gives:
```
AssertionError: Channels last conversion is only available for 3D and 4D tensors.
```
This attempts to solve the problem by simply skipping over the bias tensor for Conv operators.

Fix channels last conversion for Conv operators with a bias

---

README.md
setup.cfg
src/qonnx/custom_op/registry.py
src/qonnx/transformation/qonnx_to_qcdq.py
src/qonnx/util/convert.py
tests/transformation/test_qonnx_to_qcdq.py

This PR introduces a transformation `QuantToQCDQ` as well as an accompanying command line utility `qonnx-convert` to convert from the QONNX (`Quant`) style of representation to the QCDQ (`QuantizeLinear -> Clip -> DequantizeLinear`) style. For networks where this is possible, the QCDQ style only uses ONNX-standard nodes, which may be preferrable for some reasons (e.g. inference speed in pure `onnxruntime` or compatibility with other downstream frameworks). The behavior is tested by checking equivalence pre/post-conversion for several QONNX Model Zoo examples in `test_qonnx_to_qcdq.py`.
The following restictions apply on the `Quant` nodes for conversion:
- the scale, zero-point and bitwidth inputs for `Quant` must be statically specified by an initializer
- the bitwidth must be an integer …

QONNX to QCDQ conversion

---

README.md
src/qonnx/core/datatype.py
src/qonnx/custom_op/general/quant.py
src/qonnx/util/inference_cost.py
tests/analysis/test_inference_cost.py

- Introduce scaled integer datatypes that indicate a tensor contains scaled integers (with either tensor-wise or channel-wise scaling factors) e.g. `SCALED_INT<4>` indicates a 4-bit scaled integer. 
- The datatype inference for `Quant` layers that have nonzero zero-point or non-unit scale now marks them as scaled integers instead of defaulting to `FLOAT32`.
- The scale factors themselves are not included as part of the datatype since this would make them too verbose. Thus, these datatype are intended to be used in inference cost measurement only for now.
- When running the inference cost utility, execute `FoldConstants(exclude_op_types=[])` to get quantized weights in initializer form, thus correctly accounting for sparsity (see discussion in #49 )
See #51 for the full discussion.

Introduce scaled integer datatypes for inference cost

---

.github/workflows/test.yml
setup.cfg

This solves a dependency resolution issue preventing from installing qonnx on python 3.10, see #57. Pinning tensorflow to version 2.9.0 is necessary for python 3.10 compatibility as well. Pinning tensorflow to a more recent version, however, is not possible as it causes some tests to fail.

Pin onnxruntime and tensorflow dependencies to more recent versions

---

src/qonnx/custom_op/general/maxpoolnhwc.py
src/qonnx/custom_op/general/quantavgpool2d.py
src/qonnx/transformation/merge_onnx_models.py
tests/transformation/test_merge_onnx_models.py

When merging two ONNX models, the `MergeONNXModels` transformation currently defaults to the default opset version returned by the utility function `get_preferred_onnx_opset()`. This can lead to invalid output graphs if e.g. one of the input graphs is using an opset which is greater than the preferred opset. This PR introduces a testcase to catch this behavior, and a fix to `MergeONNXModels` that makes it pick the greater opset of the two input models when producing the output (and issuing a warning in the process).

Better opset selection for MergeONNXModels

---

setup.cfg

Bump clize and sigtools version up to avoid attr error: `ImportError: cannot import name 'AttrsInstance' from 'attr' (/tmp/home_dir/.local/lib/python3.10/site-packages/attr/__init__.py)`

Bump clize to 5.0.1 and sigtools to 4.0.1

---

src/qonnx/transformation/remove.py
tests/transformation/test_remove_unused.py

Introduce a new `RemoveUnusedNodes` that gets rid of any nodes with dangling outputs (i.e. not contributing, directly or indirectly, to any top-level output in the graph) and its associated test.

Introduce RemoveUnusedNodes

---

src/qonnx/transformation/qcdq_to_qonnx.py

When performing Q(C)DQ -> Quant conversion, simplify zero-point back to a scalar 0 value where possible.

[Convert] simplify zeropoint to scalar in QCDQ2Quant if possible

---

src/qonnx/transformation/subpixel_to_deconv.py
tests/transformation/test_subpixel_to_deconv.py

Fix: Adding dropped attributes to transposed convolution op

---

.pre-commit-config.yaml
README.md
setup.cfg
tests/transformation/test_conv_lowering.py
tests/transformation/test_expose_intermediate.py

Clean up conv lowering test infratructure by refactoring into helper function + add new testcase for rectangular depthwise dilated convolutions.
Also fixes two infrastructure issues: 
* pre-commit / black temporarily by switching to python3.10 for linter: https://github.com/pypa/pip/issues/11294
* use onnxrt>=1.16.1 to avoid onnxrt issue: https://github.com/microsoft/onnxruntime/issues/17631

Add extra conv lowering tests + fix linter issues

---

.pre-commit-config.yaml
README.md
setup.cfg
src/qonnx/custom_op/channels_last/base_wrapped_op.py
src/qonnx/custom_op/channels_last/batch_normalization.py
src/qonnx/custom_op/channels_last/conv.py
src/qonnx/custom_op/channels_last/max_pool.py
src/qonnx/custom_op/general/im2col.py
src/qonnx/transformation/channels_last.py
src/qonnx/transformation/quant_constant_folding.py
src/qonnx/util/cleanup.py
src/qonnx/util/to_channels_last.py
tests/conftest.py
tests/custom_op/test_attr.py
tests/custom_op/test_im2col.py
tests/test_dummy.py
tests/transformation/test_4d_conversion.py
tests/transformation/test_channelslast.py
tests/transformation/test_conv_lowering.py
tests/transformation/test_expose_intermediate.py
tests/transformation/test_quant_constant_folding.py
tests/transformation/test_remove_identity_ops.py
tests/transformation/test_sort_graph.py
tests/transformation/test_topk_insert.py

Intends to fix problems related to the `FoldTransposeIntoQuantInit` transformation. The transformation should only be applied if the `Transpose` node actually follows a so called `QuantInit`, these are `Quant` (or `BipolarQuant`) nodes where **all** inputs are initializers. Currently, the transform is always applied, even if just _some_ inputs have initializers. This causes problems with the shape inference, as the remaining `Quant` node does not transpose its runtime inputs. This is fixed by making the test for a node being `QuantInit` more strict.
I have tested this by running the unit tests for QONNX as well as those under `tests/transformation` over at [FINN](https://github.com/Xilinx/finn) and did not observe any issues so far. For more context please see the following issues: #77, …

Fix FoldTransposeIntoQuantInit Transformation

---

src/qonnx/transformation/infer_data_layouts.py

This is required for supporting scaled dot-product attention, which has 3 dimensional tensors with batch/head, sequence and embedding dimension.

Introduce 3D layout annotations defaulting to NWC

---

src/qonnx/transformation/extract_quant_scale_zeropt.py
tests/transformation/test_extract_quant_scale_zeropt.py

Introduces a new `ExtractQuantScaleZeroPt` transformation and its unit test to enable factoring out non-trivial scale (any scale not equal to 1) and zero-point (any zero-point not equal to 0) as stand-alone Mul/Div ops for scale and Add/Sub ops for zero-point. See example in table below (shapes in the "After" graph are inferred by regular `InferShapes` and not this new transformation).
|  Before 	|   After	|
|---	|---	|
|   <img width="155" alt="MicrosoftTeams-image (1)" src="https://github.com/fastmachinelearning/qonnx/assets/1880902/5fd80f5a-79f6-46ed-bd08-3eb83e9a2833">	|   <img width="230" alt="MicrosoftTeams-image (2)" src="https://github.com/fastmachinelearning/qonnx/assets/1880902/118577cc-f7fd-41ce-b77f-0cd04b9d2704">	|

Extract non-trivial Quant scale and zeropoint

---

README.md

Add a section to README on how to install `pre-commit` for developers intending to make pull request to `qonnx`. Also added a reminder to upgrade `pip` as part of the initial installation.

Updates to dev docs: pip upgrade, linting

---

src/qonnx/transformation/base.py

Problem: 
When debugging QONNX model transformations which can make use of applyNodeLocal using pdb, the use of multiprocessing.Pool stops the debugger from being able to stop at the exact stack frame which is created by the process forked using the multiprocessing library if the error happened there.
The stack frame can still be accessed by breakpointing right before the actual error occurs, however this would require prior knowledge of where the code breaks, which can be highly undesirable.
Solution:
Intuitively, the user would expect that if they simply set their num_workers to 1, that multiprocessing will not be called and pdb will work as expected. Thus, I propose to simply check for this case and run the applyNodeLocal() function 'as is' without mp.Pool if the worker count is set to …

Avoiding mp.Pool in case of using only 1 worker for easier pdb debugging

---

src/qonnx/transformation/lower_convs_to_matmul.py
src/qonnx/util/test.py
tests/transformation/test_conv_lowering.py

The `LowerConvsToMatMul` transformation previously only worked with `Conv` nodes that have a static initializer as the weight input. This PR extends the capabilities to deal with the case where the weights are fed by a `Quant` node, including any transpose/reshape required for the scale factors. See example below (before/after, from a 4-bit MobileNet-v1)

Preserve weight quantizer while lowering convolutions

---

src/qonnx/transformation/remove.py
tests/transformation/test_remove_identity_ops.py

`Dropout` nodes with a dropout ratio of zero (indicated by either an attribute or an optional input, depending on opset) are identity ops and can be removed from inference graphs. 
This PR adds this capability to `RemoveIdentityOps`, adds a corresponding test, and also a test for the previously-untested case of `Pad` nodes specifying no padding.

Remove Dropout with ratio=0 with RemoveIdentityOps

---

src/qonnx/transformation/remove.py
tests/transformation/test_remove_identity_ops.py

Previously, `RemoveIdentityOps` did not touch identity ops with forking outputs by excluding such nodes with a conditional. This PR removes that, and adds output forking to the corresponding test to ensure that identity nodes with forking outputs are removed correctly. These tests (in combination with all existing cases in the remove identity test) pass successfully. Example output-forked identity graph follows.
Before:
After:

Remove identity nodes with output forking

---

src/qonnx/core/datatype.py
src/qonnx/core/modelwrapper.py
src/qonnx/custom_op/general/quant.py
src/qonnx/transformation/infer_datatypes.py
src/qonnx/util/basic.py
tests/transformation/test_infer_datatypes.py

QONNX traditionally made a number of assumptions about how quantization is represented: using `float32` carrier datatypes, with quantization introduced through explicit `Quant` nodes and optionally with datatype annotations on tensors (`InferDataTypes`). Some of these baked-in assumptions cause inflexibility around other datatypes. This PR relaxes a few of these restrictions around `float16` by introducing the following changes:
* `ModelWrapper.get_tensordatatype` previously always returned `FLOAT32` for any tensor without a datatype annotation. Now an additional check is performed: if there is no datatype annotation, we look at the underlying container datatype to have the option of returning `FLOAT16` instead.
* `InferDataTypes` supports preserving `FLOAT16` either from annotations or …

Fixes for fp16 tensors and datatypes in ONNX

---

src/qonnx/transformation/channels_last.py

The channels-last conversion transpose should be able to pass over activations that are applied element-wise. Therefore, I added more nodes that can be skipped.
There is a test in hls4ml that fails without this change since it uses a Selu activation. I am not sure if more tests are needed in the qonnx repository for this.

Add more activations that a transpose can move through

---

src/qonnx/transformation/merge_onnx_models.py

We connect the output of the pre_model to the input tensor of the post_model. 
**Old behavior: The output tensor of pre_model is added to the value_info of the output model**, even though this tensor is no longer used. The input tensor of post_model is missing a value_info entry. This causes errors in FINN shape inference because no shape can be annotated to this tensor, but CustomOps expect their input tensor shape to be annotated.
**New behavior: The input tensor of post_model is added to the value_info of the output model.**

Fix incorrect value_info setting in MergeONNXModels

---

src/qonnx/transformation/create_generic_partitions.py

I had recently tried building a larger model (~517 nodes) in FINN and got stuck at CreateDataflowPartition for a long time. I did some timing measurements and tracked the longest time spent down to PartitionFromDict. Since I supply a large partition dict for a large model, this step takes a long time. The changes I'd propose here keep the functionality but speed the usage of this transform up a bit:
If the node is not in the graph, the if block is never executed, but this check still runs over the whole graph for every key in the partitioning. Moving the check out before the loop enables an early return in case the node is not in the graph.
Since the index of the node in the graph doesn't change during the function execution, it does not need to be requested in every loop iteration, and …

Updated partitioning function for PartitionFromDict

---

src/qonnx/transformation/general.py

This PR addresses the problem of not being able to assign a default configurations of the same type for different node types. For example, one could not assign the default preferred_impl_style for node type "MVAU" as "hls" and "rtl" for node type "FMPadding" in FINN. 
An example of a specialze layer config for FINN which uses the updated parser:
```
{
"Defaults": {
"preferred_impl_style": ["hls", ["MVAU"], "rtl", ["FMPadding"]]    
}
}
```
The changes made to the parser do not break old configurations.

Add support for multiple default configurations

---

setup.cfg

This PR updates the tensorflow and QKeras requirements. The keras pytests succeeded in my python 3.11-based test setup.

update tensorflow and qonnx requirements

---

src/qonnx/core/modelwrapper.py
tests/core/test_modelwrapper.py

See original PR #139 . Cherry-picked key commit, added test and re-factored to use `util.get_by_name`.

Delete tensor initializer

---

src/qonnx/core/datatype.py
tests/core/test_datatypes.py

I found some potential issue in the `resolve_datatype()` function of the `datatype.py` file:
```python
def resolve_datatype(name):
_special_types = {
"BINARY": IntType(1, False),
"BIPOLAR": BipolarType(),
"TERNARY": TernaryType(),
"FLOAT32": FloatType(),
"FLOAT16": Float16Type(),
}
if name in _special_types.keys():
return _special_types[name]
elif name.startswith("UINT"):
bitwidth = int(name.replace("UINT", ""))
return IntType(bitwidth, False)
elif name.startswith("INT"):
...
```
Looking at this function I first thought one has to pass a string for the name input. However, if the input `name` is of type for example `qonnx.core.datatype.BipolarType` with a name attribute which is covered in the `_spacial_types` dictonary (in this case Bipolar) the check `if name in _special_types.keys():` …

add type check for input name of resolve_datatype()

---

.github/workflows/pre-commit.yml
src/qonnx/transformation/insert.py
tests/transformation/test_insert_identity.py

Introduces transformations that insert `Identity` nodes in the ONNX graph at desired locations, which can either be a specified tensor (`InsertIdentity`) or all top-level input/output tensors (`InsertIdentityOnAllTopLevelIO`), as well as corresponding unit tests. This can be useful before calling transformations that do not gracefully handle edge cases where transformed tensors are top-level inputs or outputs.
Original graph: 
After `InsertIdentityOnAllTopLevelIO`:

Insert Identity nodes on given tensor and top-level graph inputs

---

setup.cfg

The coverage report (which is enabled by default when invoking `pytest`) takes up quite a bit of space in the terminal, and at the moment we don't make use of it. Opting to disable it for now.

Disable coverage in pytest

---

src/qonnx/core/modelwrapper.py
tests/core/test_modelwrapper.py

This PR fixes an issue with `set_tensor_shape` and the order of input and output tensors in the ONNX GraphProto. When setting the shape of these tensors, they used to be removed and then re-added, which potentially could mess up their order. This wasn't a problem for internal tensors (ValueInfo is unordered), but can lead to a reordering of graph.input or graph.output.
In this PR, the code now fetches the current index of the tensor in graph.input or graph.output. It then inserts the updated tensor with its new shape back into the same spot, keeping the original order intact.

Fix ModelWrapper method to preserve order of graph inputs and outputs

---

src/qonnx/core/modelwrapper.py

Moving the modelwrapper set_metadata_props and get_metadata_props to refer to the graph proto rather than the model proto. This is primary being done to enable future support for subgraph transforms in QONNX. This way when a transform is applied to a subgraph the subgraph retains the metadata and metadata does not have to be copied between parent and child graphs.

Store Metadata in Graph Proto rather than model Proto

---

src/qonnx/core/datatype.py
src/qonnx/util/basic.py
tests/core/test_datatypes.py

- vectorized implementation of value checking for all QONNX datatypes
- added value checking test cases with multi-dimensional numpy arrays
- use vectorized value checking in `sanitize_quant_values`
- TODO: check for any other internal value checks which might need to be replaced with the vectorized versions.

[DataType] vectorize checking if value is allowed for a datatype

---

src/qonnx/transformation/general.py

In rare cases, `GiveReadableTensorNames` can crash due to a collision of two tensors with the same randomly generated name. This is the case, because `model.rename_tensor` assumes that each tensor name in the graph is unique. If two tensors get assigned the same random name by `GiveRandomTensorNames` this condition is violated and the code crashes.
In this PR I fixed the problem by introducing the `GiveUniqueTensorNames` transformation, which just numbers all tensors. As a result, the naming is unique and can be used in `GiveReadableTensorNames`.
(Additionally, just iterating all tensors in a graph and assigning numbers is also a bit faster than randomly generating strings for names.)

Fix crash in GiveReadableTensorNames

---

src/qonnx/transformation/fixedpt_quantize.py
tests/transformation/test_fixedpt_quantize.py

* added the fixed-point quantize transformation, based on `fixedpt_quantize.py` from `custom/SIRA` branch.
* removed `fxpmath` dependency.
* added unit tests for op-based and dict-based quantization.

[FixedPt] add the fixed-point quantize transformation and unit tests

---

setup.cfg
src/qonnx/util/random_reseed.py
tests/custom_op/test_floatquant.py
tests/transformation/test_fixedpt_quantize.py

Fixes several recently-observed errors causing the test suite to fail
1) Fix errors with seed size limit in old-style numpy RNG API like:
```
File "mtrand.pyx", line 244, in numpy.random.mtrand.RandomState.seed
File "_mt19937.pyx", line 166, in numpy.random._mt19937.MT19937._legacy_seeding
File "_mt19937.pyx", line 180, in numpy.random._mt19937.MT19937._legacy_seeding
ValueError: Seed must be between 0 and 2**32 - 1
```
A better fix would be to follow https://github.com/numpy/numpy/issues/17079 but this requires reworking the QONNX RNGs a bit more, postponed for now.
2) Restrict onnxscript version to avoid version conflicts of the `ml_dtypes` package. newer versions of onnxscript need `ml_dtypes>=0.5` but at the moment we have `tensorflow>=2.9.0, <=2.14.1` in qonnx requirements due to …

Fix failing tests and pytest-randomly
